#!/bin/sh

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

#============ AUTOSTART ===============
sh ~/.config/bspwm/autostart.sh
sh ~/.config/bspwm/bin/dobleborder &
# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
# Execute bspwm-specific scripts.
bspfloat &

#============ RULES ==================
bspc monitor -d 1 2 3 4 5 6

rule -a kitty                       follow=on focus=on
rule -a subl                        follow=on focus=on
rule -a google-chrome-stable        follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating

#============== GENERAL CONFIGURATION ================
config border_width 10
config window_gap 20
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "#0f1015"