#!/bin/bash

# ┏━━━┓╋╋┏┓╋╋╋┏━━━┓┏┓╋╋╋╋╋┏┓
# ┃┏━┓┃╋┏┛┗┓╋╋┃┏━┓┣┛┗┓╋╋╋┏┛┗┓
# ┃┃╋┃┣┓┣┓┏╋━━┫┗━━╋┓┏╋━━┳┻┓┏┛
# ┃┗━┛┃┃┃┃┃┃┏┓┣━━┓┃┃┃┃┏┓┃┏┫┃
# ┃┏━┓┃┗┛┃┗┫┗┛┃┗━┛┃┃┗┫┏┓┃┃┃┗┓
# ┗┛╋┗┻━━┻━┻━━┻━━━┛┗━┻┛┗┻┛┗━┛

### Start 2 monitors ###
xrandr --output HDMI1 --mode 1366x768 --pos 1600x0 --rotate normal --output VGA1 --primary --mode 1600x900 --pos 0x0 --rotate normal --output VIRTUAL1 --off

### Set keymap pt_br ###
setxkbmap -model abnt2 -layout br -variant abnt2

### Set custons cursors ###
xsetroot -cursor_name left_ptr &

### Do not turn off the screen ###
xset s off &
xset -dpms &

### Set composer ###
if ps -C picom; then
  killall picom
  picom &
else
  picom &
fi

### Set wallpaper ###
### Use nitrogen
nitrogen --restore &

### Use feh
# sh ~/.fehbg &

### Set notifications ###
### Use xfce4 notify ###
# exec /usr/lib/xfce4/notifyd/xfce4-notifyd &

### Use dunst ###
dunst &

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Check for a number of outputs
outputs=$(polybar --list-monitors | cut -d":" -f1)
outputs_length=$(wc -w <<< "$outputs")

# Launch the bar
if [ "$outputs_length" == 1 ]; then
    MONITOR=$m polybar -q main &
else
    for m in $outputs; do
        MONITOR=$m polybar -q main &
        MONITOR=$m polybar -q aux &
    done
fi
