#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

#================ Default Applications ================
Term="kitty"
Browser="google-chrome-stable"
Filer="nemo"
Chat="telegram-desktop"
Music="spotify"
Editor="subl"

#================ Colors ==================
DefaultColor="#000000"
BaseColor="#0f1015"
UrgentColor="#dc8191"
InnerColor="#9a99ff"
ActiveInnerColor="#ff67ba"

#============== Windows =================

Gaps=20
Padding=1
FrameGap=10
Border=15
InnerBorder=4

# Window Settings
hc set window_gap "$Gaps"
hc set frame_padding "$Padding"
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap on

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap "$FrameGap"


hc attr theme.inner_width "$InnerBorder"
hc attr theme.border_width "$Border"
hc attr theme.floating.border_width "$Border"
hc attr theme.floating.outer_width "$InnerBorder"